### ISSUE TITLE
Something bad happened! Look into it!

### ISSUE THREAD

**Issue by bantya** [dignajar/nibbleblog#105]
Today while searching for Redirect class I was directed to your repo on Github. Following the link given for blog and demo I reached at [http://demo.nibbleblog.com](http://demo.nibbleblog.com) and saw this thing:

![paki](https://cloud.githubusercontent.com/assets/16685565/19736541/5944654c-9bcd-11e6-9214-6501f5df1039.png)

It says it is hacked by some Pakistani hackers. Please do something!

**Comment by bantya** [comment]
I think they just got it back in control!

![paki2](https://cloud.githubusercontent.com/assets/16685565/19736829/a023ac10-9bce-11e6-8d77-90081d39ea6e.png)

Closing the issue.

**Comment by dignajar** [comment]
Hello,
fixed! it's very funny because is a demo and is open for everyone, it's
really easy to hack this.

anyway, every 60minutes, the page is reloaded.

Thanks!
