### ISSUE TITLE
Installing Nibbleblog - blank screen

### ISSUE THREAD

**Issue by pathwayuk** [dignajar/nibbleblog#108]
After installing Nibbleblog, index.php just yealds a blank screen

I've check that PHP meets the requirements.  However this is a windows server running IIS - is that supported or just Apache?  

Investigated further:  It falls over in 98-plugins.bit at
$plugins_all[$class] = new $class;

with $class equal to  PLUGIN_ABOUT 

Any ideas?
malcolm

**Comment by dignajar** [comment]
could you share the php_error.log ? have you installed the plugin about ?

**Comment by pathwayuk** [comment]
Hi Diego, thanks for getting back to me.
Error log shows 
PHP Fatal error:  Cannot call constructor in ... wwwroot\blog\plugins\about\plugin.bit on line 18
which is parent::__construct(); in the PLUGIN_ABOUT class.

**Comment by pathwayuk** [comment]
Resolved.  Clearly things were missing from the files so I cleared it all and reinstalled.  I suspect it was a permissions issue on the first install.

**Comment by dignajar** [comment]
Hi,
Nibbleblog is not longer maintained, only security fixes.
Check my new project https://ww.bludit.com
Regards
