### ISSUE TITLE
Support: Passwords/Add users

### ISSUE THREAD

**Issue by MBibbington** [dignajar/nibbleblog#125]
Long story short I have lost the password and am not receiving the password reset emails to access nibbleblog. I can access all installation files on the server but cannot log in. 

Is there a way to either;

Access the existing account? 
Find the password in plain text? 
Reroute the reset emails to another address?
Add a new user with the same admin privileges?

**Comment by basteyy** [comment]
In line 81 of the admin/kernel/api/login.class.php (https://github.com/dignajar/nibbleblog/blob/master/admin/kernel/api/login.class.php#L81) you find this:

`$hash = sha1($args['password'].$_USER[0]['salt']);`

The data is stored here: /content/private/shadow.php. In the first line you fill find what you need:
`<?php $_USER[0]["uid"] = "0"; $_USER[0]["username"] = "youruser"; $_USER[0]["password"] = "somefancystring"; $_USER[0]["salt"] = "thecrazysalt"; $_USER[0]["email"] = "suprise@example.com"; ?>`

For using the password "foobar" as the login password change the shadow.php to:
`<?php $_USER[0]["uid"] = "0"; $_USER[0]["username"] = "youruser"; $_USER[0]["password"] = "b06ac7546e46105d1603d85455015dafae7300c9"; $_USER[0]["salt"] = "hF&2fkkk"; $_USER[0]["email"] = "suprise@example.com"; ?>`

Thats it.

**Comment by MBibbington** [comment]
Thank you for the explanation that has fully solved my problem and I can now login again. Much appreciated.

**Comment by dignajar** [comment]
Hi, also you can use this tool.
https://github.com/bludit/password-recovery-tool
