### ISSUE TITLE
Dark Mode? 

### ISSUE THREAD

**Issue by ktpx** [dignajar/nibbleblog#140]
Not really an issue but a request.  Is there a dark/night mode for nibbleblog? my eyes cant handle white.. of does anyone know of a dark theme. Thanks.

**Comment by Technetium1** [comment]
@ktpx [Dark Reader](https://darkreader.org/) is a temporary solution.

**Comment by ktpx** [comment]
> @ktpx [Dark Reader](https://darkreader.org/) is a temporary solution.

THanks, yes, i discovered that addon thankfully (only one that actually works).
