### ISSUE TITLE
CSRF security vulnerability

### ISSUE THREAD

**Issue by stefek99** [dignajar/nibbleblog#91]
Here: http://seclists.org/fulldisclosure/2015/Sep/4

And here: http://blog.curesec.com/article/blog/NibbleBlog-403-CSRF-46.html

**Comment by dignajar** [comment]
Fixed! I will release next week a new version.

**Comment by stefek99** [comment]
I actually emailed the person who created the report:

> I think it is easy to point mistakes
> I think it is more difficult to fix them.
> Would you be in position to submit pull request?

Link to the commit: https://github.com/dignajar/nibbleblog/commit/d5e81c7705834d49ef7e7d20f6b4247eeb850397

(I know you know - worth mentioning anyway - if you include "#91" in commit message, link to the commit will be automatically referenced here)
